// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlsuajxxvyojyawvkovr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsc3Vhanh4dnlvanlhd3Zrb3ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MDU4NDEsImV4cCI6MjA3MTM4MTg0MX0.GZIMVMcLKfBm0FZTx5vlDEYupfWEsKsmYgic_jeODiQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});